.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH HDDTEMP 1 "October 28, 2002"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
hddtemp \- Utility to monitor hard drive temperature
.SH SYNOPSIS
.B hddtemp
.RI [ options ] " disk1" ...
.SH "DESCRIPTION"
.PP
.B hddtemp 
will give you the temperature of your hard drive by reading
Self-Monitoring Analysis and Reporting Technology (S.M.A.R.T) information (on
drives that support this feature). Only modern hard drives have a temperature
sensor. hddtemp now support reading S.M.A.R.T information from SCSI drives.
.B hddtemp
can work as simple command line tool or as a daemon.

.SH OPTIONS
The programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options are included below.
.TP
.B \-b, \-\-drivebase
Display the database file that allow hddtemp to recognize a supported drive.
.TP
.B \-D, \-\-debug
Display various S.M.A.R.T. fields and their values.
Useful to find a value that seems to match the  temperature and/or to send a report.
(done for every drive supplied).
.TP
.B \-d, \-\-daemon
Execute hddtemp in daemon mode (port 7634 by default).
.TP
.B \-f, \-\-file=FILE
Specify the database file to use.
.TP
.B \-p, \-\-port=#
Port number to listen to (in daemon mode).
.TP
.B \-s, \-\-separator=C
Separator to use between fields (in daemon mode). The default separator is '|'.
.TP
.B \-q, \-\-quiet
Doesn't check if the drive drive is supported.
.TP
.B \-v, \-\-version
Display hddtemp version number.


.SH DRIVE DATABASE
If you know that your drive has a temperature sensor and is reported to be
unsupported tell me which model and which manufacturer it is, and/or just
add a new entry in /etc/hddtemp.db. Each line of hddtemp.db is 
either a commentary, a blank line or a line containing:
.TP
- a regular expression that allow hddtemp to recognize a drive or a set of drives from its model name or from a generic model name,
.TP
- a value (ATTRIBUTE_ID from S.M.A.R.T.),
.TP
- a C or an F to set the unit to Celsius or Fahrenheit,
.TP
- a description.
.PP
Feedback is welcome.

.SH DAEMON MODE
To test
.B hddtemp
in daemon mode, start
.B hddtemp
like this:
.PP
# hddtemp -d /dev/hd[abcd]
.PP
and use
.B telnet
or
.B netcat
to get a reply:
.PP
# netcat localhost 7634
.PP
Database is read once at startup, so
.B hddtemp
must be restarted if the database is updated.
.SH AUTHOR
.PP
Emmanuel Varagnat (coredump@free.fr).
.PP
This manual page was originaly written by Aurelien Jarno <aurel32@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
